DECLARE @DBName VARCHAR(255)
DECLARE @SQL NVARCHAR(255)

DECLARE FULLRECOVERY CURSOR FOR   
SELECT name  
FROM sys.databases WHERE database_id > 6

OPEN FULLRECOVERY 
FETCH NEXT FROM FULLRECOVERY INTO @DBName 
WHILE @@FETCH_STATUS = 0 
BEGIN
    --SET @SQL = 'BACKUP DATABASE ' + @DBName  + ' TO  DISK = N''NUL'' WITH NOFORMAT, NOINIT,  NAME = N''NULL'', SKIP, NOREWIND, NOUNLOAD,  STATS = 10' 
	--SET @SQL = 'ALTER DATABASE [' + @DBName + '] SET RECOVERY FULL' 
    PRINT @SQL 
    --EXECUTE sp_executesql @sql 
    FETCH next FROM FULLRECOVERY INTO @DBName 

END 

CLOSE FULLRECOVERY 
DEALLOCATE FULLRECOVERY 